name: streamit_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fast_i18n: ^5.12.1
  sqflite: ^2.3.3+1
  dio: ^5.4.0
  provider: ^6.0.2
  transparent_image: ^2.0.0
  audiofileplayer: ^2.0.1
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^10.1.0
  line_awesome_flutter: ^2.0.0
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.3
  flutter_local_notifications: ^16.3.0
  shared_preferences: ^2.0.13
  sign_in_apple: ^2.0.0
  google_sign_in: ^6.2.1
  email_validator: "^2.0.1"
  shimmer: ^3.0.0
  flutter_login_facebook: ^1.9.0
  palette_generator: ^0.3.3
  file_utils: ^1.0.1
  permission_handler: ^11.1.0
  path_provider: ^2.0.9
  flutter_downloader: ^1.11.6
  flutter_share: ^2.0.0
  package_info: ^2.0.2
  in_app_review: ^2.0.4
  url_launcher: ^6.0.20
  event_bus: ^2.0.0
  shape_of_view_null_safe: ^2.0.0
  path: ^1.8.0
  audio_session: ^0.1.6+1
  intl: ^0.18.1
  google_mobile_ads: ^4.0.0
  flash: ^3.1.0
  carousel_slider: ^4.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  build_runner: ^2.1.9
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/

fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/WorkSans-Regular.ttf
      - asset: assets/fonts/WorkSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/WorkSans-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/WorkSans-Bold.ttf
        weight: 700
